name: Setup Workflow
description: Setup workflow for GitHub Actions

runs:
    using: composite
    steps:
        - uses: pnpm/action-setup@v3.0.0
          with:
              version: 7

        - name: Setup Node.js environment
          uses: actions/setup-node@v4
          with:
              node-version: 20
              cache: pnpm

        - name: Install dependencies
          run: pnpm install
          shell: bash
