name: Test Docs

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Test build website
        run: pnpm run web:build
