name: CI

permissions: write-all

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
  merge_group:

jobs:
  skip_ci:
    runs-on: ubuntu-latest
    # Map the output to the job's outputs
    outputs:
      canSkip: ${{ steps.check.outputs.canSkip }}
    steps:
      - id: check
        uses: Legorooj/skip-ci@main

  build:
    name: Check for Successful Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: [skip_ci]
    if: ${{ needs.skip_ci.outputs.canSkip != 'true' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build

  biome:
    name: Check Formatting
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: [skip_ci]
    if: ${{ needs.skip_ci.outputs.canSkip != 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci .

  # test:
  #     name: Run Test Suites
  #     timeout-minutes: 15
  #     runs-on: ubuntu-latest
  #     needs: [skip_ci]
  #     if: ${{ needs.skip_ci.outputs.canSkip != 'true' }}
  #     steps:
  #         - name: Check out code
  #           uses: actions/checkout@v4

  #         - name: Setup
  #           uses: ./.github/actions/setup

  #         - name: Run tests
  #           run: pnpm run test
