name: Deploy Website to GitHub Pages

on:
    push:
        branches:
            - main
        paths:
            - "website/**"
            - "packages/**"

jobs:
    web:
        name: Deploy Website
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/actions/setup

            - name: Build website
              run: pnpm run web:build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./website/out
                  user_name: buapebot
                  user_email: 119761697+buapebot@users.noreply.github.com
